ask:
  name: Отправить запрос к LLM
  description: Отправка запроса к LLM с сохранением контекста
  target: {}
  fields:
    user_id:
      name: Идентификатор пользователя
      description: Уникальный идентификатор пользователя (chat_id или HA user ID)
      required: true
      example: "123456789"
      selector:
        text:
    prompt:
      name: Запрос
      description: Текстовый запрос к LLM
      required: true
      example: "Какая сегодня погода?"
      selector:
        text:
  response: true

reset_history:
  name: Сброс истории
  description: Сброс истории чата для пользователя
  target: {}
  fields:
    user_id:
      name: Идентификатор пользователя
      description: Уникальный идентификатор пользователя
      required: true
      example: "123456789"
      selector:
        text: