ask:
  description: Send a prompt to the LLM with chat history
  target: {}
  fields:
    user_id:
      description: Identifier of the user (chat_id or HA user ID)
      example: "123456789"
      required: true
      selector:
        text:
    prompt:
      description: The text prompt to send to the LLM
      example: "What is the weather today?"
      required: true
      selector:
        text:

reset_history:
  description: Reset the chat history for a user
  target: {}
  fields:
    user_id:
      description: Identifier of the user
      example: "123456789"
      required: true
      selector:
        text: